### ISSUE TITLE
List gets lost when updating data

### ISSUE THREAD

**Issue by johnnyluu** [davidroyer/vue2-editor#10] opened 2017-02-27 00:39 UTC
I have this string defined in the vue data: 
```
<p><strong>Lorem Ipsum</strong></p>
 <p>This is a test blah blah blah</p>
 <ul>
 <li>LIst item 1</li>
 <li>List item 2</li>
 <li>List item 3</li>
 </ul>
```
when I do @editor-updated="handleContent"
//method
handleContent = funcion(value){this.content = value}

The returned value doesn't have the list in it: 
```
<p><strong>Lorem Ipsum</strong></p><p>
</p><p>This is a test blah blah blah</p><p>
</p><p>



</p>
```

Is it the plugin that's stripping the list out?

**Comment by davidroyer** [comment] 2017-04-07 14:16
orry about the issues. I have updated Vue2Editor to 2.0 using v-model because of these same issues and it should resolve these problems. I'm closing this but let me know/reopen it if you have any other issues or questions.

**Closed by davidroyer** 2017-04-07 14:16 UTC

**Comment by melirofman** [comment] 2018-11-23 13:20
I am having the same issue. Did somebody find a way to fix it?

**Comment by melirofman** [comment] 2018-11-23 13:20
@davidroyer

**Comment by macoshita** [comment] 2019-06-28 17:19
This bug reproduces. ↓
https://codesandbox.io/embed/vue-template-pbluo

I fix it with the following PR↓
https://github.com/davidroyer/vue2-editor/pull/194

**Comment by macoshita** [comment] 2019-06-28 17:38
@davidroyer

**Comment by sir-script** [comment] 2020-08-11 08:25
@davidroyer It's still a bug. I've had the same issue like @ghost and @macoshita before. The pull request solves the issue. Could you take a look and check for any side effects? 
Thank you for offering such a great module.
Cheers,
Michael

**Comment by sir-script** [comment] 2020-08-13 07:45
@davidroyer It looks like the problem occurs, when the text has some whitespace between the list items, like `<ul><li>Test</li>  some whitespace characters     <li>Link2</li></ul>`

**Comment by hoodist** [comment] 2021-12-06 05:00
In my case, I used after changing like this.

**PHP**
`$html = preg_replace("/>\s+</","><", $html);`

I think you guys can be processing with regex even other language until it is resolved.
